# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'test git' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for test git

  target 'test gitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'test gitUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
